/*DROP SCHEMA public CASCADE;
CREATE SCHEMA public;*/
DROP ALL OBJECTS DELETE FILES;
CREATE TABLE IF NOT EXISTS users (
                                     id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
                                     email VARCHAR(320) NOT NULL UNIQUE,
                                     user_password VARCHAR(30) NOT NULL,
                                     CONSTRAINT pk_user PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS roles (
                                     id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
                                     role VARCHAR(25) NOT NULL UNIQUE,
                                     CONSTRAINT pk_roles PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS users_roles (
                                     id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
                                     user_id BIGINT NOT NULL,
                                     role_id BIGINT NOT NULL,
                                     CONSTRAINT pk_users_roles PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS logs (
                                    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
                                    user_id BIGINT NOT NULL,
                                    role_id BIGINT NOT NULL,
                                    date_time TIMESTAMP NOT NULL,
                                    params VARCHAR(1000) NOT NULL,
                                    CONSTRAINT pk_logs PRIMARY KEY (id),
                                    FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE,
                                    FOREIGN KEY (role_id) REFERENCES roles (id) ON DELETE CASCADE

);
