DROP ALL OBJECTS DELETE FILES;
CREATE TABLE IF NOT EXISTS users (
                                     id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
                                     email VARCHAR(320) NOT NULL UNIQUE,
                                     user_password VARCHAR(300) NOT NULL,
                                     u_role VARCHAR(25) NOT NULL,
                                     CONSTRAINT pk_user PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS logs (
                                    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
									date_time TIMESTAMP NOT NULL,
                                    user_email VARCHAR(320) NOT NULL,
                                    u_role VARCHAR(320) NOT NULL,
									url VARCHAR(1000),
                                    params VARCHAR(100) NOT NULL,
                                    result VARCHAR(500) NOT NULL,
                                    CONSTRAINT pk_logs PRIMARY KEY (id),
                                    FOREIGN KEY (user_email) REFERENCES users (email) ON DELETE CASCADE
);
